//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillionLuxury.Domain.PropertyTraces.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PropertyTraceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyTraceResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MillionLuxury.Domain.PropertyTraces.Resources.PropertyTraceResources", typeof(PropertyTraceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The property trace cannot be deleted.
        /// </summary>
        internal static string PropertyTraceCannotBeDeleted {
            get {
                return ResourceManager.GetString("PropertyTraceCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Property trace created successfully.
        /// </summary>
        internal static string PropertyTraceCreatedSuccessfully {
            get {
                return ResourceManager.GetString("PropertyTraceCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The property trace sale date must be a valid date.
        /// </summary>
        internal static string PropertyTraceDateSaleInvalidDate {
            get {
                return ResourceManager.GetString("PropertyTraceDateSaleInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The property trace sale date is required.
        /// </summary>
        internal static string PropertyTraceDateSaleRequired {
            get {
                return ResourceManager.GetString("PropertyTraceDateSaleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Property trace deleted successfully.
        /// </summary>
        internal static string PropertyTraceDeletedSuccessfully {
            get {
                return ResourceManager.GetString("PropertyTraceDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The property trace name cannot exceed 200 characters.
        /// </summary>
        internal static string PropertyTraceNameMaxLength {
            get {
                return ResourceManager.GetString("PropertyTraceNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The property trace name is required.
        /// </summary>
        internal static string PropertyTraceNameRequired {
            get {
                return ResourceManager.GetString("PropertyTraceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Property trace not found.
        /// </summary>
        internal static string PropertyTraceNotFound {
            get {
                return ResourceManager.GetString("PropertyTraceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The property ID is required.
        /// </summary>
        internal static string PropertyTracePropertyIdRequired {
            get {
                return ResourceManager.GetString("PropertyTracePropertyIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The property trace tax must be positive.
        /// </summary>
        internal static string PropertyTraceTaxMustBePositive {
            get {
                return ResourceManager.GetString("PropertyTraceTaxMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The property trace tax is required.
        /// </summary>
        internal static string PropertyTraceTaxRequired {
            get {
                return ResourceManager.GetString("PropertyTraceTaxRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Property trace updated successfully.
        /// </summary>
        internal static string PropertyTraceUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("PropertyTraceUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The property trace value must be positive.
        /// </summary>
        internal static string PropertyTraceValueMustBePositive {
            get {
                return ResourceManager.GetString("PropertyTraceValueMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The property trace value is required.
        /// </summary>
        internal static string PropertyTraceValueRequired {
            get {
                return ResourceManager.GetString("PropertyTraceValueRequired", resourceCulture);
            }
        }
    }
}
