//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillionLuxury.Domain.Owners.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OwnerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OwnerResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MillionLuxury.Domain.Owners.Resources.OwnerResources", typeof(OwnerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The owner address cannot exceed 250 characters.
        /// </summary>
        internal static string OwnerAddressMaxLength {
            get {
                return ResourceManager.GetString("OwnerAddressMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The owner address is required.
        /// </summary>
        internal static string OwnerAddressRequired {
            get {
                return ResourceManager.GetString("OwnerAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An owner with this name already exists.
        /// </summary>
        internal static string OwnerAlreadyExists {
            get {
                return ResourceManager.GetString("OwnerAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The owner birthday must be a valid date.
        /// </summary>
        internal static string OwnerBirthdayInvalidDate {
            get {
                return ResourceManager.GetString("OwnerBirthdayInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The owner birthday is required.
        /// </summary>
        internal static string OwnerBirthdayRequired {
            get {
                return ResourceManager.GetString("OwnerBirthdayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The owner cannot be deleted because it has associated properties.
        /// </summary>
        internal static string OwnerCannotBeDeleted {
            get {
                return ResourceManager.GetString("OwnerCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Owner created successfully.
        /// </summary>
        internal static string OwnerCreatedSuccessfully {
            get {
                return ResourceManager.GetString("OwnerCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Owner deleted successfully.
        /// </summary>
        internal static string OwnerDeletedSuccessfully {
            get {
                return ResourceManager.GetString("OwnerDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The owner photo format is not valid. Only JPEG, PNG, GIF, BMP, WebP and SVG are allowed.
        /// </summary>
        internal static string OwnerInvalidPhotoFormat {
            get {
                return ResourceManager.GetString("OwnerInvalidPhotoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An owner with the name &apos;{0}&apos; already exists.
        /// </summary>
        internal static string OwnerNameAlreadyExists {
            get {
                return ResourceManager.GetString("OwnerNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The owner name cannot exceed 100 characters.
        /// </summary>
        internal static string OwnerNameMaxLength {
            get {
                return ResourceManager.GetString("OwnerNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The owner name is required.
        /// </summary>
        internal static string OwnerNameRequired {
            get {
                return ResourceManager.GetString("OwnerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Owner not found.
        /// </summary>
        internal static string OwnerNotFound {
            get {
                return ResourceManager.GetString("OwnerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The owner photo is too large. Maximum size is 5MB.
        /// </summary>
        internal static string OwnerPhotoTooLarge {
            get {
                return ResourceManager.GetString("OwnerPhotoTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Owner updated successfully.
        /// </summary>
        internal static string OwnerUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("OwnerUpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
